jobs:
- job:
  displayName: ubuntu-16.04
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name myEnvironment
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      conda install -c conda-forge --yes --quiet --name myEnvironment python=$PYTHON_VERSION numpy numba xarray scipy sundials sympy typing_extensions
      pip install pytest pytest-azurepipelines hypothesis pytest-cov
    displayName: Install Anaconda packages
  - bash: |
      source activate myEnvironment
      pip install -e .
    displayName: Install package
  - bash: |
      source activate myEnvironment
      pytest --cov pysundials_cffi --cov-report html
    displayName: pytest

- job:
  displayName: macOS-10.13
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create -c conda-forge --yes --quiet --name myEnvironment python=$PYTHON_VERSION numpy numba xarray scipy sundials sympy typing_extensions
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      pip install pytest pytest-azurepipelines hypothesis
    displayName: Install Anaconda packages
  - bash: |
      source activate myEnvironment
      pip install -e .
    displayName: Install package
  - bash: |
      source activate myEnvironment
      pytest
    displayName: pytest
- job:
  displayName: vs2017-win2016
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create -c conda-forge --yes --quiet --name myEnvironment python=%PYTHON_VERSION% numpy numba xarray scipy sundials sympy typing_extensions
    displayName: Create Anaconda environment

  - script: |
      call activate myEnvironment
      pip install pytest pytest-azurepipelines hypothesis
    displayName: Install Anaconda packages
  - script: |
      call activate myEnvironment
      pip install -e .
    displayName: Install package and build extension
  - script: |
      call activate myEnvironment
      pytest
    displayName: pytest
